-- liquibase formatted sql
--changeset suman.gajmer:1

--preconditions onFail:CONTINUE onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM roles
INSERT INTO roles (description, icon, name, navigation, parent_name, permission, position, ui_group_name, version)
VALUES ('Root', '', 'Root', 'NONE', 'ROOT', 'NONE', 0, 'NONE',0),
       ('Venodrs', 'msi-vendor', 'Venodrs', '/vendor', 'Root', 'VENDOR', 1, 'NONE',0),
       ('Create Vendor', '', 'Create Vendor', 'create', 'Venodrs', 'CREATE_BANK', 1, 'Venodrs',0),
       ('View Vendor', '', 'View Vendor', 'view', 'Venodrs', 'VIEW_VENDOR', 2, 'Venodrs',0),
       ('Modify Vendor', '', 'Modify Vendor', 'edit', 'Venodrs', 'MODIFY_VENDOR', 3, 'Venodrs',0),
       ('Delete Vendor', '', 'Delete Vendor', 'delete', 'Venodrs', 'DELETE_VENDOR', 4, 'Venodrs',0),
       ('Block Vendor', '', 'Block Vendor', 'block', 'Venodrs', 'BLOCK_VENDOR', 5, 'Venodrs',0),
       ('UnBlock Vendor', '', 'UnBlock Vendor', 'unblock', 'Venodrs', 'UNBLOCK_VENDOR', 6, 'Venodrs',0),
       ('Reopen Vendor', '', 'Reopen Vendor', 'reopen', 'Venodrs', 'REOPEN_VENDOR', 7, 'Venodrs',0),
       ('Unlock Vendor Controller', '', 'Unlock Vendor Controller', 'unlock', 'Venodrs', 'UNLOCK_VENDOR_ADMIN', 8,
        'Venodrs',0),
       ('Reset Password Vendor Controller', '', 'Reset Password Vendor Controller', 'reset', 'Venodrs',
        'RESET_PASSWORD_VENDOR_ADMIN', 9, 'Venodrs',0),
       ('Resend Account Activation Link Vendor Controller', '', 'Resend Account Activation Link Vendor Controller',
        'resend', 'Venodrs', 'RESEND_ACCOUNT_ACTIVATION_LINK_VENDOR_ADMIN', 10, 'Venodrs',0),
       ('Resend Vendor Activation Link', '', 'Resend Vendor Activation Link', 'resendVendor', 'Venodrs',
        'RESEND_VENDOR_ACTIVATION_LINK', 11, 'Venodrs',0),
       ('Resend Vendor And Vendor Controller Activation Link', '',
        'Resend Vendor And Vendor Controller Activation Link', 'resendVendorAndVendorAdmin', 'Venodrs',
        'RESEND_VENDOR_AND_VENDOR_ADMIN_ACTIVATION_LINK', 12, 'Venodrs',0),
       ('Vendor Setup', '', 'Vendor Setup', 'setup', 'Venodrs', 'VENDOR_SETUP', 13, 'Venodrs',0),
       ('view Vendor Setup', '', 'View Vendor Setup', 'view', 'Vendor Setup', 'VIEW_VENDOR_SETUP', 1, 'Vendor Setup',0),
       ('Modify Vendor Setup', '', 'Modify Vendor Setup', 'edit', 'Vendor Setup', 'MODIFY_VENDOR_SETUP', 2,
        'Vendor Setup',0),
       ('Reset Two Factor Authentication Vendor Controller', '', 'Reset Two Factor Authentication Vendor Controller',
        'resetTwoFactorAuth', 'Venodrs', 'RESET_TWO_FACTOR_AUTHENTICATION_VENDOR_CONTROLLER', 14, 'Venodrs',0),
       ('Reports', 'msi-financial-presentation', 'Reports', '/reports', 'Root', 'REPORTS', 4, 'NONE',0),
       ('Vendor Reports', 'msi-Vendor-reports', 'Vendor Reports', 'vendorReports', 'Reports', 'VIEW_VENDOR_REPORTS', 3,
        'Reports',0),
       ('Customers', 'msi-user', 'Customers', '/customer', 'Root', 'CUSTOMER', 10, 'NONE',0),
       ('View Customer', '', 'View Customer', 'view', 'Customers', 'VIEW_CUSTOMER', 1, 'Customers',0),
       ('Delete Customer', '', 'Delete Customer', 'delete', 'Customers', 'DELETE_CUSTOMER', 2, 'Customers',0),
       ('Block Customer', '', 'Block Customer', 'block', 'Customers', 'BLOCK_CUSTOMER', 3, 'Customers',0),
       ('UnBlock Customer', '', 'UnBlock Customer', 'unblock', 'Customers', 'UNBLOCK_CUSTOMER', 4, 'Customers',0),
       ('Reopen Customer', '', 'Reopen Customer', 'reopen', 'Customers', 'REOPEN_CUSTOMER', 5, 'Customers',0),
       ('Unlock Customer', '', 'Unlock Customer', 'unlock', 'Customers', 'UNLOCK_CUSTOMER', 6, 'Customers',0),
       ('Reset Password Customer', '', 'Reset Password Customer', 'reset', 'Customers', 'RESET_PASSWORD_CUSTOMER', 7,
        'Customers',0),
       ('Resend Account Activation Link Customer', 'VENDOR_LOAN_REPORTS', 'Resend Account Activation Link Customer',
        'resend', 'Customers', 'RESEND_ACCOUNT_ACTIVATION_LINK_CUSTOMER', 8, 'Customers',0),
       ('Edit Customer', '', 'Edit Customer', 'edit', 'Customers', 'EDIT_CUSTOMER', 10, 'Customers',0),
       ('Admin Users', 'msi-moderator', 'Admin Users', '/adminUser', 'Root', 'ADMIN_USER', 11, 'NONE',0),
       ('Create Admin User', '', 'Create Admin User', 'create', 'Admin Users', 'CREATE_ADMIN_USER', 1, 'Admin Users',0),
       ('Modify Admin User', 'msi-edit', 'Modify Admin User', 'edit', 'Admin Users', 'MODIFY_ADMIN_USER', 2,
        'Admin Users',0),
       ('View Admin User', 'msi-view', 'View Admin User', 'view', 'Admin Users', 'VIEW_ADMIN_USER', 3, 'Admin Users',0),
       ('Delete Admin User', '', 'Delete Admin User', 'delete', 'Admin Users', 'DELETE_ADMIN_USER', 4, 'Admin Users',0),
       ('Block Admin User', '', 'Block Admin User', 'block', 'Admin Users', 'BLOCK_ADMIN_USER', 5, 'Admin Users',0),
       ('UnBlock Admin User', '', 'UnBlock Admin User', 'unblock', 'Admin Users', 'UNBLOCK_ADMIN_USER', 6,
        'Admin Users',0),
       ('Reopen Admin User', '', 'Reopen Admin User', 'reopen', 'Admin Users', 'REOPEN_ADMIN_USER', 7, 'Admin Users',0),
       ('Unlock Admin User', '', 'Unlock Admin User', 'unlock', 'Admin Users', 'UNLOCK_ADMIN_USER', 8, 'Admin Users',0),
       ('Reset Password Admin User', '', 'Reset Password Admin User', 'reset', 'Admin Users',
        'RESET_PASSWORD_ADMIN_USER', 9, 'Admin Users',0),
       ('Resend Account Activation Link Admin User', '', 'Resend Account Activation Link Admin User', 'resend',
        'Admin Users', 'RESEND_ACCOUNT_ACTIVATION_LINK_ADMIN_USER', 10, 'Admin Users',0),
       ('Reset Two Factor Authentication Admin User', '', 'Reset Two Factor Authentication Admin User',
        'resetTwoFactorAuth', 'Admin Users', 'RESET_TWO_FACTOR_AUTHENTICATION_ADMIN_USER', 11, 'Admin Users',0),
       ('Settings', 'msi-settings', 'Settings', '/setting', 'Root', 'SETTING', 13, 'NONE',0),
       ('Style Guide', 'msi-web-design', 'Style Guide', '/styleGuide', 'Root', 'STYLE_GUIDE', 14, 'NONE',0),
       ('Vendor Profile', 'msi-Vendor', 'Vendor Profile', '/vendorProfile', 'Root', 'VENDOR_PROFILE', 2, 'NONE',0),
       ('View Vendor Profile', '', 'View Vendor Profile', 'view', 'Vendor Profile', 'VIEW_VENDOR_PROFILE', 1,
        'Vendor Profile',0),
       ('Modify Vendor Logo', '', 'Modify Vendor Logo', 'modifyVendorLogo', 'Vendor Profile', 'MODIFY_VENDOR_LOGO', 2,
        'Vendor Profile',0),
       ('Email Templates', 'msi-email-settings', 'Email Templates', 'email', 'Settings', 'EMAIL_TEMPLATE', 1,
        'Settings',0),
       ('View Email Template', '', 'View Email Template', 'view', 'Email Templates', 'VIEW_EMAIL_TEMPLATE', 1,
        'Email Templates',0),
       ('Modify Email Template', '', 'Modify Email Template', 'edit', 'Email Templates', 'MODIFY_EMAIL_TEMPLATE', 2,
        'Email Templates',0),
       ('SMS Templates', 'msi-sms-settings', 'SMS Templates', 'sms', 'Settings', 'SMS_TEMPLATE', 2, 'Settings',0),
       ('View SMS Template', '', 'View SMS Template', 'view', 'SMS Templates', 'VIEW_SMS_TEMPLATE', 1, 'SMS Templates',0),
       ('Modify SMS Template', '', 'Modify SMS Template', 'edit', 'SMS Templates', 'MODIFY_SMS_TEMPLATE', 2,
        'SMS Templates',0),
       ('Reminders', 'msi-bell-ring', 'Reminders', 'reminders', 'Settings', 'REMINDERS', 3, 'Settings',0),
       ('View Reminder', '', 'View Reminder', 'view', 'Reminders', 'VIEW_REMINDER', 1, 'Reminders',0),
       ('Modify Reminder', '', 'Modify Reminder', 'edit', 'Reminders', 'MODIFY_REMINDER', 2, 'Reminders',0),
       ('My Profile', 'msi-user', 'My Profile', '/my-profile', 'Root', 'MY_PROFILE', 12, 'NONE',0),
       ('View Profile', '', 'View Profile', 'view', 'My Profile', 'VIEW_PROFILE', 1, 'My Profile',0),
       ('Edit Profile', '', 'Edit Profile', 'edit', 'My Profile', 'EDIT_PROFILE', 2, 'My Profile',0),
       ('Access Groups', 'msi-staff', 'Access Groups', 'group', 'Settings', 'GROUP', 4, 'Settings',0),
       ('Create Access Group', '', 'Create Access Group', 'create', 'Access Groups', 'CREATE_GROUP', 1,
        'Access Groups',0),
       ('View Access Group', '', 'View Access Group', 'view', 'Access Groups', 'VIEW_GROUP', 2, 'Access Groups',0),
       ('Modify Access Group', '', 'Modify Access Group', 'edit', 'Access Groups', 'MODIFY_GROUP', 3, 'Access Groups',0),
       ('Delete Access Group', '', 'Delete Access Group', 'delete', 'Access Groups', 'DELETE_GROUP', 4,
        'Access Groups',0),
       ('Password Policy', 'msi-umbrella', 'Password Policy', 'passwordPolicy', 'Settings', 'PASSWORD_POLICY', 5,
        'Settings',0),
       ('View Password Policy', '', 'View Password Policy', 'view', 'Password Policy', 'VIEW_PASSWORD_POLICY', 1,
        'Password Policy',0),
       ('Modify Password Policy', '', 'Modify Password Policy', 'edit', 'Password Policy', 'MODIFY_PASSWORD_POLICY', 2,
        'Password Policy',0),
       ('Admin Configuration', 'msi-administrative-tool', 'Admin Configuration', 'adminConfiguration', 'Settings',
        'ADMIN_CONFIGURATION', 6, 'Settings',0),
       ('View Admin Configuration', '', 'View Admin Configuration', 'view', 'Admin Configuration',
        'VIEW_ADMIN_CONFIGURATION', 1, 'Admin Configuration',0),
       ('Modify Admin Configuration', '', 'Modify Admin Configuration', 'edit', 'Admin Configuration',
        'MODIFY_ADMIN_CONFIGURATION', 2, 'Admin Configuration',0);


--changeset suman.gajmer:2
UPDATE roles AS r
    INNER JOIN roles AS parent ON r.parent_name = parent.name
    SET r.parent_role = parent.id;


